spring:
  jackson:
    time-zone: UTC
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

urlAPIBack: http://localhost:8080

numcolonnes:
  bhl:
    numVoie : 1
    codeMissionDepart : 12
    codeMissionArrivee : 2
    garesTrainArrivee : 7
    garesTrainDepart : 17
    heureArrivee : 3
    heureDepart : 13
    nombreColonnes : 33

  ratp:
    codeMission : 10
    codeADC : 9
    numeroRame : 0
    manoeuvre : 14
    typeEvenement : 1
    numVoieDepart : 8
    numVoieArrivee : 9
    gareArrivee : 8
    gareDepart : 5
    heureArrivee : 2
    heureDepart : 3
    manoeuvreVide : "-"
    manoeuvreGarage : "G"
    manoeuvreDegarage : "D"
    manoeuvreRetournement : "R"
    typeEvenementDepart :
      - "MSC"
      - "MSV"
    typeEvenementArrivee :
      - "MEC"
      - "MEV"

  pacific:
    codeMission : 0
    typeMission: 1
    heureDebut: 3
    heureFin: 6
    codeADC: 8

gares:
  - nom: MITRY
    alias: MY
    quais:
      - id : 3
      - id : 5
      - id: SAS 3
      - id: SAS 5
      - id: V1
      - id: V2
      - id: GI
  - nom: CDG2
    alias: RYR
    quais:
      - id: 11
      - id: 12
  - nom: L2-PEX
    alias: PEX
    quais:
      - id: T54
      - id: T53
      - id: T52
      - id: T51
      - id: VM
  - nom: MASSY
    alias: MP
    quais:
      - id: V1
      - id: QA
      - id: QB
      - id: V2
      - id: VZ
      - id: PA
  - nom: ORSAY
    alias: OV
    quais:
      - id: Q1
      - id: Q2
      - id: QZ
  - nom: StREMY
    alias: SR
    quais:
      - id: Q1
      - id: Q2
      - id: Q3
  - nom: ROBINSON
    alias: RO
    quais:
      - id: Q1
      - id: Q2
      - id: Q4
  - nom: ROISSY-1
    alias: RSY
    quais:
      - id: V1BIS
      - id: V2BIS
      - id: V1
      - id: V2
  - nom: AULNAY-SOUS-BOIS
    alias: AB
    quais:
      - id: 23
      - id: 21
      - id: 22
      - id: 24
  - nom: GARE_DU_NORD(souterraine)
    alias: GDS
    quais:
      - id: 41
      - id: 43
      - id: 44
      - id: 42
  - nom: GARE_DU_NORD(surface)
    alias: PNB
    quais:
      - id: 19
      - id: 20
      - id: 21
      - id: 22
      - id: 30
      - id: 31
      - id: 32
      - id: 33
      - id: 34
      - id: 35
      - id: 36