urlAPIBack: http://localhost:8080

gares:
  - nom: Mitry
    alias: MY
    quais:
      - id : V5
      - id : V3
      - id: SAS5
      - id : SAS3
      - id: V1
      - id: V2
      - id: GA
  - nom: Gare2
    alias: valeur1
    quais:
      - id: Quai3
      - id: Quai4
