spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

numcolonnes:
  bhl:
    numVoie : 2
    codeMissionDepart : 13
    codeMissionArrivee : 3
    garesTrainArrivee : 8
    garesTrainDepart : 18
    heureArrivee : 4
    heureDepart : 14

  ratp:
    numVoie : 2
    codeMissionDepart : 13
    codeMissionArrivee : 3
    garesTrainArrivee : 8
    gareArrivee : 18
    heureArrivee : 4
    heureDepart : 14

urlAPIBack: http://localhost:8080

gares:
  - nom: MITRY
    alias: MY
    quais:
      - id : V5
      - id : V3
      - id: SAS5
      - id : SAS3
      - id: V1
      - id: V2
      - id: GA
  - nom: CDG2
    alias: RYR
    quais:
      - id: V11
      - id: V12
  - nom: L2-PEX
    alias: PEX
    quais:
      - id: T54
      - id: T53
      - id: T52
      - id: T51
      - id: VM
  - nom: MASSY
    alias: MPA
    quais:
      - id: QA
      - id: QB
      - id: VZ
      - id: PA
  - nom: ORSAY
    alias: ORS
    quais:
      - id: Q1
      - id: Q2
      - id: QZ
  - nom: StREMY
    alias: REM
    quais:
      - id: Q1
      - id: Q2
      - id: Q3
  - nom: ROBINSON
    alias: ROB
    quais:
      - id: Q1
      - id: Q2
      - id: Q4
  - nom: ROISSY-1
    alias: RSY
    quais:
      - id:
  - nom: AULNAY-SOUS-BOIS
    alias: AB
    quais:
      - id:
  - nom: GARE_DU_NORD(souterraine)
    alias: GDS
    quais:
      - id:
  - nom: GARE_DU_NORD(surface)
    alias: PNB
    quais:
      - id: